(() => {
  const DATA=window.P6_XIAOHEIYUN_LANGCHAIN;if(!DATA||!window.P6ShotcraftRenderers)return;
  const R=window.P6ShotcraftRenderers.create(DATA),$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const stage=$('#stage'),root=$('#sceneRoot'),chapterLabel=$('#chapterLabel'),countLabel=$('#countLabel'),chapterNav=$('#chapterNav'),status=$('#status'),scrub=$('#scrub'),narration=$('#narration');
  const prevBtn=$('#prevBtn'),nextBtn=$('#nextBtn'),playBtn=$('#playBtn'),pauseBtn=$('#pauseBtn'),soundBtn=$('#soundBtn'),fullscreenBtn=$('#fullscreenBtn'),recordBtn=$('#recordBtn'),recordMeta=$('#recordMeta');
  const scenes=DATA.scenes||[],CH=Object.fromEntries((DATA.chapters||[]).map(c=>[c.id,c])),params=new URLSearchParams(location.search);
  let current=Math.max(0,Math.min(scenes.length-1,Number(params.get('scene')||1)-1)),localAudio={},ownedUrls=[],sceneTl=null,playing=false,paused=false,raf=0,fallbackStarted=0,fallbackOffset=0,currentProgress=0,lastCue=-1;
  const QA=params.get('qa')==='1',SOUND_KEY='project6.aigc-xiaoheiyun-agent.sound.enabled',DB_NAME='project6-aigc-xiaoheiyun-agent-audio',STORE='audio';let soundEnabled=localStorage.getItem(SOUND_KEY)!=='0';
  if(window.gsap&&window.DrawSVGPlugin)gsap.registerPlugin(DrawSVGPlugin);if(window.gsap&&window.MotionPathPlugin)gsap.registerPlugin(MotionPathPlugin);
  function fit(){const viewer=$('.viewer'),frame=$('.stage-frame');if(!viewer||!frame)return;const r=viewer.getBoundingClientRect(),scale=Math.min(r.width/1920,r.height/1080);frame.style.width=`${1920*scale}px`;frame.style.height=`${1080*scale}px`;stage.style.transform=`scale(${scale})`;stage.style.transformOrigin='0 0'}
  function buildTimeline(){if(sceneTl)sceneTl.kill();if(!window.gsap)return null;const tl=gsap.timeline({paused:true,defaults:{ease:'power3.out'}});gsap.set('.cue',{opacity:0,y:24,filter:'blur(6px)'});gsap.set('.cue-0',{opacity:1,y:0,filter:'blur(0px)'});gsap.set('.draw-line',{drawSVG:'0%'});gsap.set('.path-token,.time-orb,.loop-token',{opacity:0});gsap.set('.scrub-line',{left:'8%'});gsap.set('.contrast-after',{clipPath:'inset(0 92% 0 0)'});gsap.set('.mini-progress i,.latency i,.capability-row i',{scaleX:0,scaleY:.15,transformOrigin:'left bottom'});[1,2,3,4].forEach((n,i)=>tl.to(`.cue-${n}`,{opacity:1,y:0,filter:'blur(0px)',duration:8,stagger:.65},12+i*20));if($$('.draw-line').length)tl.to('.draw-line',{drawSVG:'100%',duration:30,stagger:1.1,ease:'power2.inOut'},15);if($('.visual-contrast')){tl.to('.scrub-line',{left:'76%',duration:8,ease:'power3.out'},20).to('.scrub-line',{left:'70%',duration:5,ease:'power2.inOut'},28).to('.scrub-line',{left:'40%',duration:17,ease:'power2.inOut'},54);tl.to('.contrast-after',{clipPath:'inset(0 24% 0 0)',duration:8,ease:'power3.out'},20).to('.contrast-after',{clipPath:'inset(0 30% 0 0)',duration:5},28).to('.contrast-after',{clipPath:'inset(0 60% 0 0)',duration:17,ease:'power2.inOut'},54)}if($('.visual-timeline')&&window.MotionPathPlugin){const orb=$('.time-orb'),path=$('#timelinePath');if(orb&&path)tl.to(orb,{opacity:1,duration:2},14).to(orb,{duration:66,motionPath:{path,align:path,alignOrigin:[.5,.5]},ease:'none'},16)}if($('.visual-system')&&window.MotionPathPlugin){const token=$('.loop-token'),path=$('#sysLoopA');if(token&&path)tl.to(token,{opacity:1,duration:2},24).to(token,{duration:46,motionPath:{path,align:path,alignOrigin:[.5,.5]},ease:'none'},26)}if($('.visual-network')&&window.MotionPathPlugin){const token=$('.token-a'),path=$('#pA');if(token&&path)tl.to(token,{opacity:1,duration:2},24).to(token,{duration:28,motionPath:{path,align:path,alignOrigin:[.5,.5]},ease:'power1.inOut'},26).to(token,{opacity:0,duration:3},54);const t2=$('.token-b'),p2=$('#pE');if(t2&&p2)tl.to(t2,{opacity:1,duration:2},39).to(t2,{duration:28,motionPath:{path:p2,align:p2,alignOrigin:[.5,.5]},ease:'power1.inOut'},41).to(t2,{opacity:0,duration:3},69)}if($('.visual-stack'))tl.to('.stack-world',{rotationX:3,rotationY:-7,y:-34,duration:20,ease:'power2.inOut'},38).to('.stack-world',{rotationX:0,rotationY:0,y:0,duration:14},66);if($('.visual-code'))tl.fromTo('.stream-row',{x:-24},{x:0,duration:12,stagger:2},32).to('.latency i',{scaleX:1,duration:18,stagger:3},52);if($('.visual-project'))tl.to('.mini-progress i',{scaleX:1,duration:20,stagger:3},45);if($('.visual-timeline'))tl.to('.capability-row i',{scaleY:1,duration:24,stagger:2},48);tl.eventCallback('onUpdate',()=>{currentProgress=tl.progress();updateCueHighlight(currentProgress)});return tl}
  function cueIndexForProgress(p){return p<.18?0:p<.38?1:p<.60?2:p<.80?3:4}function updateCueHighlight(p){const idx=cueIndexForProgress(p);$$('.cue-step').forEach((el,i)=>el.classList.toggle('active',i+1===idx));if(idx!==lastCue&&idx>0&&playing&&!QA){playSfx(idx===4?'chime':idx===1?'whoosh':'tick');lastCue=idx}}
  let audioCtx=null;function playSfx(kind='tick'){if(!soundEnabled||QA)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);let f1=kind==='whoosh'?180:kind==='chime'?660:520,f2=kind==='whoosh'?680:kind==='chime'?990:420,d=kind==='whoosh'?.18:kind==='chime'?.22:.06;osc.type=kind==='chime'?'sine':'triangle';osc.frequency.setValueAtTime(f1,now);osc.frequency.exponentialRampToValueAtTime(f2,now+d);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(kind==='chime'?.025:.015,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+d);osc.start(now);osc.stop(now+d+.02)}catch(_){}}
  function sceneDuration(s){return Math.max(7000,Math.min(14500,(s.narration||s.title||'').length*115))}function drive(){if(!playing||paused)return;let p=currentProgress;if(localAudio[scenes[current].id]&&narration.duration&&Number.isFinite(narration.duration))p=Math.min(1,narration.currentTime/narration.duration);else p=Math.min(1,(performance.now()-fallbackStarted+fallbackOffset)/sceneDuration(scenes[current]));sceneTl?.progress(p);currentProgress=p;if(p>=.999){advance();return}raf=requestAnimationFrame(drive)}
  async function playCurrent(){if(playing&&!paused)return;if(paused){resume();return}playing=true;paused=false;lastCue=cueIndexForProgress(currentProgress)-1;playBtn&&(playBtn.textContent='▶ 播放中');pauseBtn&&(pauseBtn.textContent='⏸ 暂停');const id=scenes[current].id;if(localAudio[id]){narration.src=localAudio[id];narration.currentTime=0;narration.muted=!soundEnabled;narration.onended=advance;try{await narration.play();status&&(status.textContent=`${id} · LOCAL AUDIO · CUE SYNC`)}catch{fallbackStarted=performance.now();fallbackOffset=currentProgress*sceneDuration(scenes[current]);drive();return}drive()}else{fallbackStarted=performance.now();fallbackOffset=currentProgress*sceneDuration(scenes[current]);status&&(status.textContent=`${id} · VISUAL CUE SYNC`);drive()}}
  function pause(){if(!playing)return;if(!paused){paused=true;cancelAnimationFrame(raf);raf=0;narration.pause();pauseBtn&&(pauseBtn.textContent='▶ 继续');status&&(status.textContent='PAUSED · CUE LOCKED')}else resume()}function resume(){if(!playing)return;paused=false;pauseBtn&&(pauseBtn.textContent='⏸ 暂停');if(localAudio[scenes[current].id])narration.play().catch(()=>{});else{fallbackStarted=performance.now();fallbackOffset=currentProgress*sceneDuration(scenes[current])}drive()}function advance(){cancelAnimationFrame(raf);raf=0;narration.pause();if(current<scenes.length-1){current++;render();playCurrent()}else{playing=false;playBtn&&(playBtn.textContent='▶ 播放');status&&(status.textContent='FULL VIDEO COMPLETE · 42/42')}}
  function render(){cancelAnimationFrame(raf);raf=0;narration.pause();playing=false;paused=false;currentProgress=0;lastCue=-1;const s=scenes[current];root.innerHTML=R.renderScene(s);chapterLabel&&(chapterLabel.innerHTML=`<i></i>${DATA.project.toUpperCase()}`);countLabel&&(countLabel.textContent=`${String(current+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`);chapterNav&&(chapterNav.textContent=CH[s.chapter]?.title||'');status&&(status.textContent=`${s.id} · ${s.title} · CUE READY`);if(scrub){scrub.max=scenes.length-1;scrub.value=current}sceneTl=buildTimeline();sceneTl?.progress(QA?1:.035);if(QA)setTimeout(runQA,80);narration.src=localAudio[s.id]||'';fit()}
  function show(n){current=Math.max(0,Math.min(scenes.length-1,n));render()}function syncSound(){if(narration)narration.muted=!soundEnabled;if(soundBtn){soundBtn.textContent=soundEnabled?'🔊 声音开':'🔇 声音关';soundBtn.classList.toggle('primary',soundEnabled);soundBtn.setAttribute('aria-pressed',soundEnabled?'true':'false')}}
  prevBtn&&(prevBtn.onclick=()=>show(current-1));nextBtn&&(nextBtn.onclick=()=>show(current+1));playBtn&&(playBtn.onclick=playCurrent);pauseBtn&&(pauseBtn.onclick=pause);soundBtn&&(soundBtn.onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem(SOUND_KEY,soundEnabled?'1':'0');syncSound()});fullscreenBtn&&(fullscreenBtn.onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.shell')?.requestFullscreen?.());recordBtn&&(recordBtn.onclick=()=>{const u=new URL('./record.html?v=65-p2-final',location.href);const w=window.open(u.href,'project6RecorderControllerP2','popup=yes,width=1500,height=920,resizable=yes');if(!w)alert('浏览器阻止了录制控制台，请允许本站弹出窗口后再点一次。')});scrub&&(scrub.oninput=e=>show(Number(e.target.value)));addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1);if(e.key===' '){e.preventDefault();playing?pause():playCurrent()}});addEventListener('resize',fit);window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const m=e.data||{};if(m.type==='P6_LOCAL_AUDIO'&&m.files){localAudio={...m.files};render()}if(m.type==='P6_CLEAR_AUDIO'){localAudio={};render()}});
  function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function restoreAudio(){try{ownedUrls.forEach(URL.revokeObjectURL);ownedUrls=[];const db=await openDB(),tx=db.transaction(STORE,'readonly'),store=tx.objectStore(STORE),map={};for(let i=1;i<=scenes.length;i++){const id=String(i).padStart(3,'0'),b=await new Promise(r=>{const q=store.get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>r(null)});if(b){const u=URL.createObjectURL(b);ownedUrls.push(u);map[id]=u}}db.close();if(Object.keys(map).length){localAudio=map;render();status&&(status.textContent=`LOCAL AUDIO ${Object.keys(map).length}/${scenes.length}`)}}catch(e){console.warn('P2 audio restore failed',e)}}
  function runQA(){const issues=[],st=stage.getBoundingClientRect(),checks=$$('.qa-check');checks.forEach(el=>{const r=el.getBoundingClientRect(),sx=st.width/1920,sy=st.height/1080,rel={l:(r.left-st.left)/sx,t:(r.top-st.top)/sy,r:(r.right-st.left)/sx,b:(r.bottom-st.top)/sy};if(rel.l<-3||rel.t<-3||rel.r>1923||rel.b>1083)issues.push(`OUT:${el.className}`);if(el.scrollWidth>el.clientWidth+3||el.scrollHeight>el.clientHeight+3)issues.push(`CLIP:${el.className}`)});const report={scene:scenes[current].id,title:scenes[current].title,recipe:R.RECIPES[scenes[current].id],issues,checks:checks.length};document.documentElement.dataset.qa=JSON.stringify(report)}
  syncSound();fit();render();if(!QA)restoreAudio();if(recordMeta)recordMeta.textContent='P2 · 42 SCENES · CUE SYNC · SHOTCRAFT FINAL';addEventListener('beforeunload',()=>{ownedUrls.forEach(URL.revokeObjectURL);cancelAnimationFrame(raf)});
})();
