(()=>{
  const DATA=window.P6_XIAOHEIYUN_LANGCHAIN;if(!DATA)return;
  const scenes=DATA.scenes.slice(0,4),$=s=>document.querySelector(s),stage=$('#stage'),root=$('#sceneRoot'),chapterLabel=$('#chapterLabel'),countLabel=$('#countLabel'),chapterNav=$('#chapterNav'),status=$('#status'),scrub=$('#scrub'),narration=$('#narration');
  const prevBtn=$('#prevBtn'),nextBtn=$('#nextBtn'),playBtn=$('#playBtn'),pauseBtn=$('#pauseBtn'),soundBtn=$('#soundBtn'),fullscreenBtn=$('#fullscreenBtn'),recordBtn=$('#recordBtn'),recordMeta=$('#recordMeta');
  let current=Math.max(0,Math.min(3,Number(new URLSearchParams(location.search).get('scene')||1)-1)),playing=false,paused=false,fallbackTimer=null,fallbackStart=0,fallbackLeft=0,sceneTl=null,localAudio={},ownedUrls=[];
  const SOUND_KEY='project6.aigc-xiaoheiyun-agent.sound.enabled',DB_NAME='project6-aigc-xiaoheiyun-agent-audio',STORE='audio';let soundEnabled=localStorage.getItem(SOUND_KEY)!=='0';
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pts=arr=>`<div class="points">${arr.map((x,i)=>`<div class="point anim"><b>0${i+1}</b><span>${esc(x)}</span></div>`).join('')}</div>`;
  function fit(){const viewer=$('.viewer'),frame=$('.stage-frame'),r=viewer.getBoundingClientRect(),scale=Math.min(r.width/1920,r.height/1080);frame.style.width=`${1920*scale}px`;frame.style.height=`${1080*scale}px`;stage.style.transform=`scale(${scale})`}addEventListener('resize',fit);document.addEventListener('fullscreenchange',fit);
  function scene001(s){return `<section class="scene s001"><div class="grid"><div class="copy"><div class="date anim">2022.11.30 · ${esc(s.kicker)}</div><h1 class="anim">ChatGPT<br>把 <em>AI 的大门</em><br>推向了普通人。</h1><p class="anim">第一次，普通人不需要懂代码，也能直接和大模型对话。真正震撼的不是“它会聊天”，而是 AI 的使用门槛突然掉到了几乎为零。</p><div class="impact"><div class="metric anim"><b>自然语言入口</b><span>不用学习复杂命令，像聊天一样使用模型。</span></div><div class="metric anim"><b>通用能力感知</b><span>写作、解释、总结、编程在同一个入口里发生。</span></div></div></div><div class="door-card anim"><div class="door"><div class="door-light anim"></div><div class="panel-left anim"></div><div class="panel-right anim"></div><div class="door-label anim"><b>CHATGPT</b><span>PUBLIC AI INTERFACE</span></div><div class="door-foot"><div class="anim"><strong>Before</strong><br>AI 多数停留在技术圈和特定应用里。</div><div class="anim"><strong>After</strong><br>每个人都能直接把工作问题交给模型。</div></div></div></div><aside class="rail"><div class="card anim"><h3>为什么它会引爆全球？</h3>${pts(['交互方式：从命令与 API 变成自然语言。','反馈速度：问题几乎立刻得到结构化回应。','通用性：一个入口覆盖大量脑力任务。'])}</div><div class="card anim"><div class="quote">那一刻最容易产生的错觉是：<em>“贾维斯是不是快来了？”</em></div><div class="points"><div class="point"><b>A</b><span>会回答问题</span></div><div class="point"><b>B</b><span>会生成内容</span></div><div class="point"><b>C</b><span>但还不会主动替你执行完整任务</span></div></div></div></aside></div><div class="footer-note">SCENE 001 · 时间 / 事件 / 变化 / 用户感知 / 下一矛盾</div></section>`}
  function scene002(s){return `<section class="scene s002"><div class="scene-title top-left compact"><div class="eyebrow anim">${esc(s.kicker)} · ${esc(s.sourceTime)}</div><h1 class="anim">它已经很会说，<br>却还不够<em>会做</em>。</h1></div><div class="body"><div class="side"><div class="card anim"><h3>Chatbot 已经会什么？</h3>${pts(['写作、总结、翻译、解释知识','单轮问答和内容生成','根据 Prompt 给出一次性结果'])}</div><div class="card anim"><h3>为什么仍然不是 Agent？</h3>${pts(['你不问，它基本不动','不知道任务现在做到哪一步','不会自己决定何时搜索、何时调工具、何时重试'])}</div><div class="ability-grid"><div class="ability anim"><b>被动响应</b><small>User → Model → Answer</small></div><div class="ability anim"><b>缺少状态</b><small>没有连续任务进度</small></div></div></div><div class="gap"><strong class="anim">≠</strong><span>EXECUTION GAP</span></div><div class="side"><div class="card anim"><h3>Agent 必须补上的能力</h3>${pts(['Planning：把目标拆成步骤','Tool Use：搜索、网页、文件、API','State：保存中间结果与当前进度','Loop：根据结果继续下一步'])}</div><div class="ability-grid"><div class="ability anim"><b>主动行动</b><small>Goal → Plan → Act</small></div><div class="ability anim"><b>持续迭代</b><small>Observe → Decide → Continue</small></div></div></div><div class="compare-table anim"><table class="info-table"><thead><tr><th>维度</th><th>Chatbot</th><th>Agent</th></tr></thead><tbody><tr><td>目标</td><td>回答问题</td><td>完成任务</td></tr><tr><td>执行</td><td>单次生成</td><td>多步规划 + 工具调用 + 继续判断</td></tr><tr><td>状态</td><td>对话上下文</td><td>任务进度 / 中间结果 / 恢复点</td></tr><tr><td>结果</td><td>给你一个答案</td><td>把事情真正往前推进</td></tr></tbody></table></div></div></section>`}
  function scene003(s){return `<section class="scene s003"><div class="scene-title top-center compact"><div class="eyebrow anim">${esc(s.kicker)} · ${esc(s.sourceTime)}</div><h1 class="anim">AI 正在从 <em>CHAT</em> 走向 <em>ACT</em></h1></div><div class="timeline"><div class="rail anim"></div><div class="stops"><div class="stop anim"><div class="event"><div class="year">2022</div><b>ChatGPT</b><small>大众化对话入口。核心还是生成与问答。</small></div></div><div class="stop anim"><div class="event"><div class="year">2023</div><b>AutoGPT</b><small>自动拆任务、循环执行的 Agent 思路出圈。</small></div></div><div class="stop anim"><div class="event"><div class="year">2024</div><b>Computer Use</b><small>模型开始看屏幕、点击、输入和操作软件。</small></div></div><div class="stop anim"><div class="event"><div class="year">2025</div><b>Deep Research</b><small>多步骤搜索、阅读、推理、整合进入产品能力。</small></div></div><div class="stop anim"><div class="event"><div class="year">2026</div><b>Long-running Agent</b><small>长任务、工具链、团队协作逐步进入生产环境。</small></div></div></div></div><div class="summary"><div class="card anim"><h3>Planning</h3><p>会拆任务，而不是只回答。</p></div><div class="card anim"><h3>Tool Use</h3><p>会搜、会读、会调接口、会操作。</p></div><div class="card anim"><h3>Iteration</h3><p>会根据中间结果决定下一步。</p></div><div class="card anim"><h3>Long-running</h3><p>任务从几秒回答变成分钟、小时级执行。</p></div></div><div class="footer-note">SCENE 003 · 每个年份都解释能力边界变化</div></section>`}
  function scene004(s){return `<section class="scene s004"><div class="scene-title top-left compact"><div class="eyebrow anim">${esc(s.kicker)} · ${esc(s.sourceTime)}</div><h1 class="anim">企业真正需要的，<br>是<em>会交付结果的 AI</em>。</h1></div><div class="body"><div class="matrix"><div class="card anim"><h3>自动化工作流</h3><p>Agent 自己读取规则、调用系统并回写结果。</p><div class="flow"><span>读取工单</span><span>查规则</span><span>调 API</span><span>写结果</span></div></div><div class="card anim"><h3>AI 数据分析</h3><p>自动取数、整理指标、发现异常、形成决策线索。</p><div class="flow"><span>取数</span><span>分析</span><span>异常</span><span>报告</span></div></div><div class="card anim"><h3>7×24 智能客服</h3><p>真正价值在订单、退款、物流、工单等业务系统闭环。</p><div class="flow"><span>理解问题</span><span>查知识</span><span>执行业务</span><span>确认结果</span></div></div><div class="card anim"><h3>数字员工</h3><p>企业开始从“会不会说”转向“能不能持续完成任务”。</p><div class="flow"><span>Context</span><span>Tools</span><span>State</span><span>Recovery</span></div></div></div><aside class="rail"><div class="trend anim"><h3>为什么 Agent 岗位需求会升温？</h3><div class="bar-row"><span>业务价值</span><div class="bar"><i style="width:90%"></i></div><strong>高</strong></div><div class="bar-row"><span>降本增效</span><div class="bar"><i style="width:86%"></i></div><strong>强</strong></div><div class="bar-row"><span>工程难度</span><div class="bar"><i style="width:78%"></i></div><strong>高</strong></div><div class="bar-row"><span>岗位需求</span><div class="bar"><i style="width:93%"></i></div><strong>↑</strong></div></div><div class="formula anim"><h3>企业需要的不是更大的聊天框</h3><p>而是一套能理解目标、接入业务、调用工具、管理状态，并持续把任务完成的执行系统。</p><div class="formula-row"><div>业务接入</div><span>+</span><div>工具执行</div><span>+</span><div>持续交付</div></div></div></aside></div></section>`}
  const renderers=[scene001,scene002,scene003,scene004];
  function animate(){if(sceneTl)sceneTl.kill();if(!window.gsap)return;sceneTl=gsap.timeline({defaults:{ease:'power3.out'}});gsap.set('.anim',{opacity:0,y:24});sceneTl.to('.anim',{opacity:1,y:0,duration:.58,stagger:.045},.05);const left=$('.panel-left'),right=$('.panel-right');if(left&&right){gsap.set([left,right],{rotationY:0,transformPerspective:900});sceneTl.to(left,{rotationY:-46,duration:1.15,ease:'power2.inOut'},.35).to(right,{rotationY:46,duration:1.15,ease:'power2.inOut'},.35)}}
  function stopPlayback(){clearTimeout(fallbackTimer);fallbackTimer=null;narration.pause();narration.onended=null;playing=false;paused=false;playBtn.textContent='▶ 播放';pauseBtn.textContent='⏸ 暂停'}
  function render(){const s=scenes[current];root.innerHTML=renderers[current](s);const ch=DATA.chapters.find(c=>c.id===s.chapter);chapterLabel.innerHTML=`<i></i>${esc(DATA.project.toUpperCase())}`;countLabel.textContent=`${String(current+1).padStart(2,'0')} / ${String(DATA.totalScenes).padStart(2,'0')}`;chapterNav.textContent=ch?ch.title:'CHAPTER 1';status.textContent=`${s.id} · ${s.title}${localAudio[s.id]?' · LOCAL AUDIO':''}`;scrub.value=current;animate();narration.src=localAudio[s.id]||''}
  function show(n){stopPlayback();current=Math.max(0,Math.min(3,n));render()}
  function sceneDuration(){return Math.max(7500,Math.min(15000,(scenes[current].narration||'').length*110))}
  function advance(){if(current<3){current++;render();playCurrent()}else{stopPlayback();status.textContent='ANCHOR REVIEW COMPLETE'}}
  async function playCurrent(){playing=true;paused=false;playBtn.textContent='▶ 播放中';pauseBtn.textContent='⏸ 暂停';if(sceneTl)sceneTl.play();const id=scenes[current].id;if(localAudio[id]){narration.src=localAudio[id];narration.currentTime=0;narration.muted=!soundEnabled;narration.onended=advance;try{await narration.play();status.textContent=`${id} · LOCAL AUDIO PLAYING`}catch{startFallback()}}else startFallback()}
  function startFallback(ms=sceneDuration()){fallbackLeft=ms;fallbackStart=performance.now();fallbackTimer=setTimeout(advance,ms);status.textContent=`${scenes[current].id} · VISUAL TIMING`}
  function pause(){if(!playing)return;if(!paused){paused=true;pauseBtn.textContent='▶ 继续';status.textContent='PAUSED';if(sceneTl)sceneTl.pause();if(!narration.paused)narration.pause();if(fallbackTimer){fallbackLeft=Math.max(0,fallbackLeft-(performance.now()-fallbackStart));clearTimeout(fallbackTimer);fallbackTimer=null}}else{paused=false;pauseBtn.textContent='⏸ 暂停';if(sceneTl)sceneTl.play();if(narration.src&&localAudio[scenes[current].id])narration.play().catch(()=>startFallback(fallbackLeft||sceneDuration()));else startFallback(fallbackLeft||sceneDuration())}}
  function syncSound(){narration.muted=!soundEnabled;soundBtn.textContent=soundEnabled?'🔊 声音开':'🔇 声音关';soundBtn.setAttribute('aria-pressed',soundEnabled?'true':'false');soundBtn.classList.toggle('primary',soundEnabled)}
  prevBtn.onclick=()=>show(current-1);nextBtn.onclick=()=>current<3?show(current+1):(status.textContent='LOCKED · 先验收 Scene 001–004');playBtn.onclick=()=>paused?pause():playing?null:playCurrent();pauseBtn.onclick=pause;soundBtn.onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem(SOUND_KEY,soundEnabled?'1':'0');syncSound()};fullscreenBtn.onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.shell').requestFullscreen?.();recordBtn.onclick=()=>{const u=new URL('./record.html?v=64-p2a5',location.href);const w=window.open(u.href,'project6RecorderControllerP2','popup=yes,width=1500,height=920,resizable=yes');if(!w)alert('浏览器阻止了录制控制台，请允许本站弹出窗口后再点一次。')};scrub.max=3;scrub.oninput=e=>show(Number(e.target.value));addEventListener('keydown',e=>{if(e.key==='ArrowRight')nextBtn.click();if(e.key==='ArrowLeft')prevBtn.click();if(e.key===' '){e.preventDefault();playing?pause():playCurrent()}});
  window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const m=e.data||{};if(m.type==='P6_LOCAL_AUDIO'&&m.files){localAudio={...m.files};status.textContent=`LOCAL AUDIO ${Object.keys(localAudio).length}/${DATA.scenes.length}`;render()}if(m.type==='P6_CLEAR_AUDIO'){localAudio={};render()}});
  function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function restoreAudio(){try{ownedUrls.forEach(URL.revokeObjectURL);ownedUrls=[];const db=await openDB(),tx=db.transaction(STORE,'readonly'),store=tx.objectStore(STORE),map={};for(let i=1;i<=DATA.scenes.length;i++){const id=String(i).padStart(3,'0'),b=await new Promise(r=>{const q=store.get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>r(null)});if(b){const u=URL.createObjectURL(b);ownedUrls.push(u);map[id]=u}}db.close();if(Object.keys(map).length){localAudio=map;render();status.textContent=`LOCAL AUDIO ${Object.keys(map).length}/${DATA.scenes.length}`}}catch(e){console.warn('P2 audio restore failed',e)}}
  if(recordMeta)recordMeta.textContent='P2 · LOCAL TTS READY';syncSound();fit();render();restoreAudio();if(window.parent&&window.parent!==window)window.parent.postMessage({type:'P6_PLAYER_READY'},location.origin);addEventListener('beforeunload',()=>ownedUrls.forEach(URL.revokeObjectURL));
})();