(function(g){
  const P={
    '001':{visual:'portal',shot:'spotlight-hero-card + integration-hub-map',motion:'portalFlow',logic:'事件 → 入口变化 → 大众扩散',hero:'ChatGPT',labels:['自然语言','普通用户','写作/解释/编程','AI 大众入口']},
    '002':{visual:'chasm',shot:'before-after-slider-scrub + motion-path-handoff',motion:'gapCross',logic:'能力对比 → 执行鸿沟 → Agent 补齐能力',hero:'会说 ≠ 会做',labels:['回答','规划','工具','状态','持续执行']},
    '003':{visual:'timeline',shot:'timeline-travel + camera-follow',motion:'timelineTravel',logic:'时间演进 → 能力边界扩张',hero:'CHAT → ACT',labels:['ChatGPT','AutoGPT','Computer Use','Deep Research','Long-running']},
    '004':{visual:'enterpriseMap',shot:'integration-hub-map + ring-diagram-annotation-reveal',motion:'hubDispatch',logic:'Agent 核心能力 → 四类企业场景 → 业务价值',hero:'AGENT AT WORK',labels:['工作流','数据分析','智能客服','数字员工']},
    '005':{visual:'outcomeBoard',shot:'before-after-slider-scrub + result-counter',motion:'resultSweep',logic:'评价标准变化：回答质量 → 业务结果',hero:'ANSWER → OUTCOME',labels:['订单','工单','分析','客服']},
    '006':{visual:'workflowLoop',shot:'cycle-glass-node-morph + route-trace',motion:'loopRoute',logic:'读取上下文 → 判断 → 调工具 → 检查 → 调整 → 继续',hero:'AI IN THE LOOP',labels:['Context','Plan','API','Observe','Adjust','Continue']},
    '007':{visual:'usecaseOrbit',shot:'orbit-ring-title-open + card-orbit',motion:'orbitCases',logic:'不同岗位场景围绕同一 Agent 能力内核',hero:'24 × 7',labels:['客服','分析','运营','反馈闭环']},
    '008':{visual:'careerStairs',shot:'basic-3d-scene + camera-step',motion:'careerClimb',logic:'技能层级递进：Model API → Agent System → AI Product',hero:'FROM APP TO AGENT',labels:['Model API','Agent System','AI Product']},
    '009':{visual:'agentAnatomy',shot:'exploded-system-map + label-reveal',motion:'anatomyBuild',logic:'Agent 是系统组合，不是 Prompt',hero:'SYSTEM > PROMPT',labels:['Model','Tools','Context','Memory','State','Recovery','Permission','Observability']},
    '010':{visual:'reliabilityRun',shot:'fracture-recovery + error-cascade',motion:'failureCascade',logic:'长任务越长 → 失败点越多 → 必须支持恢复',hero:'RELIABILITY',labels:['Tool Error','Format Drift','Context Growth','Interrupt','Retry','Resume']},
    '011':{visual:'frameworkBridge',shot:'bridge-reveal + spotlight-hero-card',motion:'bridgeAssemble',logic:'复杂度两岸之间，用框架搭桥',hero:'LANGCHAIN',labels:['Model','Tools','Messages','Context','Middleware']},
    '012':{visual:'interfaceHub',shot:'integration-hub-map + connector-snap',motion:'hubConnect',logic:'统一接口把模型、工具、MCP、中间件接起来',hero:'BUILD FASTER',labels:['create_agent','Tools','MCP','Middleware','Observability']},
    '013':{visual:'eraSplit',shot:'before-after-slider-scrub + title-demote-to-label',motion:'eraMorph',logic:'旧 Chain 心智 → 新 Agent Framework 心智',hero:'CHAIN → AGENT',labels:['Prompt Chain','Parser','Agent Loop','Tools','State']},
    '014':{visual:'codeRuntime',shot:'typing-code-block + code-to-runtime',motion:'codeExecute',logic:'create_agent 代码 → 运行时组件 → Agent Loop',hero:'CREATE_AGENT',labels:['Model','Tools','Prompt','Middleware']},
    '015':{visual:'graphDAG',shot:'graph-route + draw-svg-trace',motion:'graphRoute',logic:'State + Node + Edge + Branch 形成可控运行图',hero:'CONTROL THE FLOW',labels:['State','Node','Edge','Branch','Checkpoint','Human Review']},
    '016':{visual:'harnessLayers',shot:'card-stack + camera-push',motion:'layerStack',logic:'越复杂的任务，需要越高层的 Harness 能力',hero:'BATTERIES INCLUDED',labels:['Planning','Filesystem','Subagents','Context']},
    '017':{visual:'traceWaterfall',shot:'ai-stream-response + trace-waterfall',motion:'traceStream',logic:'一次 Agent 执行拆成模型、工具、延迟、错误、评估',hero:'TRACE · EVAL',labels:['Model Call','Tool Call','Latency','Error','Evaluate']},
    '018':{visual:'ecosystemStack',shot:'stack-parallax + camera-push',motion:'stackDepth',logic:'Deep Agents → LangChain → LangGraph → LangSmith 分层关系',hero:'THE STACK',labels:['Deep Agents','LangChain','LangGraph','LangSmith']},
    '019':{visual:'courseGap',shot:'before-after-slider-scrub + doc-swipe',motion:'courseCompare',logic:'旧教程入口与当前官方入口错位',hero:'API CHANGED',labels:['旧 Chain API','历史范式','当前 create_agent','Agent-first']},
    '020':{visual:'knowledgeFilter',shot:'filter-sieve + title-demote-to-label',motion:'filterPass',logic:'历史包袱被过滤，只保留今天要用的能力',hero:'CURRENT FIRST',labels:['Agent','Tools','Context','create_agent','RAG','MCP','LangGraph']},
    '021':{visual:'mentalMap',shot:'ring-diagram-annotation-reveal + map-fold',motion:'mapReveal',logic:'先建立概念地图，再学习 API',hero:'UNDERSTAND FIRST',labels:['Agent 是什么','LangChain 做什么','LangGraph 何时用']},
    '022':{visual:'courseRoadmap',shot:'timeline-travel + chapter-pan',motion:'roadmapTravel',logic:'四阶段课程路线依次展开',hero:'4 PARTS',labels:['Agent 入门','Agent 进阶','RAG','LangGraph']},
    '023':{visual:'chapterLaunch',shot:'lead-word-zoom-assemble + stage-open',motion:'chapterLaunch',logic:'Part 1 目标：把 Agent 从概念跑成可执行系统',hero:'AGENT BASICS',labels:['AI 通识','Models','Messages','Tools']},
    '024':{visual:'toolCalling',shot:'integration-hub-map + tool-call-handoff',motion:'toolCall',logic:'模型判断 → 生成参数 → 调函数 → 拿结果 → 继续回答',hero:'CALL THE WORLD',labels:['Function Tool','Schema','Tool Call','Result']},
    '025':{visual:'contextWindow',shot:'ring-diagram-annotation-reveal + context-compress',motion:'contextLayers',logic:'不同上下文进入窗口，并动态保留/压缩/注入',hero:'RIGHT INFO',labels:['System Prompt','History','User Data','Tool Result','Dynamic Context','Compression']},
    '026':{visual:'traceFilmstrip',shot:'ai-stream-response + trace-scrub',motion:'traceScrub',logic:'运行轨迹逐步展开，定位慢点和错误点',hero:'SEE THE LOOP',labels:['Trace','Latency','Error']},
    '027':{visual:'projectFlow',shot:'card-stack + completion-sweep',motion:'projectComplete',logic:'理解需求 → 调用工具 → 结果 → 再回答，形成生活 Agent 闭环',hero:'FROM DEMO TO USEFUL',labels:['理解','调用','结果','闭环']},
    '028':{visual:'chapterLaunch2',shot:'title-demote-to-label + scene-push',motion:'chapterShift',logic:'Part 2 从能跑转向产品工程',hero:'AGENT ADVANCED',labels:['Runtime','Context','Middleware']},
    '029':{visual:'middlewareGate',shot:'cycle-glass-node-morph + interception-gates',motion:'gateSequence',logic:'请求穿过多个工程规则，再进入模型/工具',hero:'GUARD THE LOOP',labels:['Guardrail','Dynamic Model','Business Logic','Tool Policy','Cost','Audit']},
    '030':{visual:'mcpBus',shot:'integration-hub-map + connector-plug',motion:'plugBus',logic:'Agent 通过标准协议连接多种外部能力',hero:'CONNECT',labels:['Tools','Resources','Prompts','Protocol']},
    '031':{visual:'multiAgent',shot:'orbit-ring-title-open + delegation-flight',motion:'delegateOrbit',logic:'主 Agent 拆任务并委派给不同角色，再汇总',hero:'DELEGATE',labels:['Supervisor','Researcher','Writer','Reviewer']},
    '032':{visual:'agentUI',shot:'ai-stream-response + stateful-ui',motion:'uiStream',logic:'Agent 内部状态被映射为真实产品交互',hero:'SHIP IT',labels:['Chat UI','Streaming','Tool State','User Flow']},
    '033':{visual:'ragIntro',shot:'lead-word-zoom-assemble + retrieve-generate',motion:'ragOpen',logic:'问题 → 检索资料 → 放进上下文 → 生成回答',hero:'RAG',labels:['Retrieve','Context','Generate']},
    '034':{visual:'vectorPipeline',shot:'pipeline-build + vector-space',motion:'vectorFlow',logic:'文档 → 切片 → Embedding → Vector Store → 语义检索',hero:'DOCUMENT → VECTOR',labels:['Chunk','Embedding','Vector Store','Semantic Search']},
    '035':{visual:'retrievalFunnel',shot:'funnel + before-after-slider-scrub',motion:'funnelDrop',logic:'Query Rewrite → Recall → Rerank → Filter → Compress',hero:'RECALL → RERANK',labels:['Query Rewrite','Recall','Rerank','Filter','Compress']},
    '036':{visual:'knowledgeProject',shot:'card-stack + completion-sweep',motion:'kbProject',logic:'导入 → 检索 → 回答 → 评估，形成可扩展知识底座',hero:'KNOWLEDGE AGENT',labels:['Ingest','Retrieve','Answer','Evaluate']},
    '037':{visual:'langgraphOpen',shot:'lead-word-zoom-assemble + graph-draw',motion:'graphOpen',logic:'Agent Loop 不够时，把状态与流转显式画出来',hero:'LANGGRAPH',labels:['State','Node','Edge']},
    '038':{visual:'stateMachine',shot:'cycle-glass-node-morph + graph-route',motion:'stateRoute',logic:'状态沿节点流转，支持分支、循环、子图和恢复',hero:'REMEMBER THE PROCESS',labels:['State','Branch','Loop','Subgraph','Checkpoint']},
    '039':{visual:'approvalCheckpoint',shot:'pause-resume + before-after-slider-scrub',motion:'approvalPause',logic:'关键动作前暂停 → 人工审核 → 恢复执行',hero:'PAUSE · REVIEW · RESUME',labels:['Pause','Review','Approve','Resume']},
    '040':{visual:'finalSystem',shot:'basic-3d-scene + integration-hub-map',motion:'finalAssemble',logic:'Tools + Context + RAG + MCP + LangGraph 汇聚成完整助手',hero:'PERSONAL AGENT',labels:['Tools','Context','RAG','MCP','LangGraph']},
    '041':{visual:'decisionMap',shot:'ring-diagram-annotation-reveal + route-picker',motion:'mapDecision',logic:'遇到不同问题，选择不同技术层',hero:'KNOW WHAT TO USE',labels:['LangChain','RAG','MCP','LangGraph']},
    '042':{visual:'finale',shot:'orbit-ring-title-open + title-demote-to-label + spotlight-hero-card',motion:'finale',logic:'Model API → Agent System → Build Agents',hero:'BUILD AGENTS',labels:['Model API','Agent System','Start Building']}
  };
  g.P6_SEMANTIC42_PLANS=P;
})(window);
