(()=>{
  const DATA=window.P6_XIAOHEIYUN_LANGCHAIN,R=window.P6Semantic42,PLANS=window.P6_SEMANTIC42_PLANS||{};if(!DATA||!R)return;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],stage=$('#stage'),root=$('#sceneRoot'),chapterLabel=$('#chapterLabel'),countLabel=$('#countLabel'),chapterNav=$('#chapterNav'),status=$('#status'),scrub=$('#scrub'),narration=$('#narration');
  const prevBtn=$('#prevBtn'),nextBtn=$('#nextBtn'),playBtn=$('#playBtn'),pauseBtn=$('#pauseBtn'),soundBtn=$('#soundBtn'),fullscreenBtn=$('#fullscreenBtn'),recordBtn=$('#recordBtn'),recordMeta=$('#recordMeta');
  const scenes=DATA.scenes||[],CH=Object.fromEntries((DATA.chapters||[]).map(c=>[c.id,c])),params=new URLSearchParams(location.search);
  let current=Math.max(0,Math.min(scenes.length-1,Number(params.get('scene')||1)-1)),sceneTl=null,playing=false,paused=false,raf=0,fallbackStarted=0,fallbackOffset=0,currentProgress=0,lastCue=-1,localAudio={},ownedUrls=[];
  const QA=params.get('qa')==='1',SOUND_KEY='project6.aigc-xiaoheiyun-agent.sound.enabled',DB_NAME='project6-aigc-xiaoheiyun-agent-audio',STORE='audio';let soundEnabled=localStorage.getItem(SOUND_KEY)!=='0';
  if(window.gsap&&window.DrawSVGPlugin)gsap.registerPlugin(DrawSVGPlugin);if(window.gsap&&window.MotionPathPlugin)gsap.registerPlugin(MotionPathPlugin);
  function fit(){const viewer=$('.viewer'),frame=$('.stage-frame');if(!viewer||!frame)return;const r=viewer.getBoundingClientRect(),scale=Math.min(r.width/1920,r.height/1080);frame.style.width=`${1920*scale}px`;frame.style.height=`${1080*scale}px`;stage.style.transform=`scale(${scale})`;stage.style.transformOrigin='0 0'}
  function safeTo(tl,sel,vars,at){if($(sel))tl.to(sel,vars,at)}
  function pathMove(tl,tokenSel,pathSel,at,dur=42,ease='none'){const token=$(tokenSel),path=$(pathSel);if(token&&path&&window.MotionPathPlugin){tl.to(tokenSel,{opacity:1,duration:2},at).to(tokenSel,{duration:dur,motionPath:{path,align:path,alignOrigin:[.5,.5]},ease},at+2)}}
  function baseTimeline(){const tl=gsap.timeline({paused:true,defaults:{ease:'power3.out'}});gsap.set('.cue',{opacity:0,y:22,filter:'blur(5px)'});gsap.set('.cue-0',{opacity:1,y:0,filter:'blur(0px)'});if($$('.sv-path').length)gsap.set('.sv-path',{drawSVG:'0%'});gsap.set('.sv-token',{opacity:0});[1,2,3,4].forEach((n,i)=>tl.to(`.cue-${n}`,{opacity:1,y:0,filter:'blur(0px)',duration:8,stagger:.35},8+i*22));if($$('.sv-path').length)tl.to('.sv-path',{drawSVG:'100%',duration:28,stagger:.8,ease:'power2.inOut'},12);return tl}
  function applyMotion(tl,s){const p=PLANS[s.id]||{},m=p.motion||'';
    if(m==='portalFlow'){safeTo(tl,'.portal-door',{scale:1.035,duration:14,yoyo:true,repeat:1,ease:'sine.inOut'},28);pathMove(tl,'.portal-token','#p3',24,46,'power1.inOut');safeTo(tl,'.audience',{y:-8,duration:8,stagger:.8,yoyo:true,repeat:1},48)}
    else if(m==='gapCross'){safeTo(tl,'.cliff.left',{x:-18,duration:12},18);safeTo(tl,'.cliff.right',{x:18,duration:12},18);pathMove(tl,'.gap-token','#gapPath',28,34,'power1.inOut');safeTo(tl,'.gap',{scale:1.04,duration:7,yoyo:true,repeat:1},48)}
    else if(m==='timelineTravel'){pathMove(tl,'.timeline-token','#timelinePath',16,70,'none');safeTo(tl,'.milestone',{scale:1.035,duration:5,stagger:10,yoyo:true,repeat:1},20)}
    else if(m==='hubDispatch'){pathMove(tl,'.enterprise-token.t1','#e1',24,24,'power1.inOut');pathMove(tl,'.enterprise-token.t2','#e4',48,24,'power1.inOut');safeTo(tl,'.enterprise-core',{scale:1.04,duration:8,yoyo:true,repeat:1},42)}
    else if(m==='resultSweep'){safeTo(tl,'.score-ring',{rotation:210,duration:24,ease:'power2.inOut'},18);safeTo(tl,'.outcome-item>i:after',{scaleX:1,duration:18,stagger:2},52);safeTo(tl,'.outcome-new',{scale:1.04,duration:10,yoyo:true,repeat:1},66)}
    else if(m==='loopRoute'){pathMove(tl,'.loop-token','#loopRoute',18,68,'none');safeTo(tl,'.loop-node',{scale:1.04,duration:4,stagger:8,yoyo:true,repeat:1},20);safeTo(tl,'.loop-core',{rotation:2,duration:12,yoyo:true,repeat:1},44)}
    else if(m==='orbitCases'){safeTo(tl,'.orbit-card.o1',{x:90,y:30,rotation:2,duration:24},22);safeTo(tl,'.orbit-card.o2',{x:-90,y:30,rotation:-2,duration:24},22);safeTo(tl,'.orbit-card.o3',{x:100,y:-20,duration:24},46);safeTo(tl,'.orbit-card.o4',{x:-100,y:-20,duration:24},46);safeTo(tl,'.orbit-core',{scale:1.045,duration:8,yoyo:true,repeat:1},70)}
    else if(m==='careerClimb'){pathMove(tl,'.career-token','#careerPath',18,65,'power1.inOut');safeTo(tl,'.career-step',{z:40,y:-10,duration:9,stagger:12,yoyo:true,repeat:1},22)}
    else if(m==='anatomyBuild'){safeTo(tl,'.anatomy-part',{scale:1.06,duration:6,stagger:4,yoyo:true,repeat:1},24);safeTo(tl,'.anatomy-core',{scale:1.045,duration:14,yoyo:true,repeat:1},52)}
    else if(m==='failureCascade'){safeTo(tl,'.run-token',{opacity:1,x:1450,duration:66,ease:'none'},16);safeTo(tl,'.failure-point',{x:8,duration:.35,stagger:8,yoyo:true,repeat:3,ease:'power1.inOut'},22);safeTo(tl,'.recovery-lane',{scale:1.05,duration:8,yoyo:true,repeat:1},70)}
    else if(m==='bridgeAssemble'){pathMove(tl,'.bridge-token','#bridgePath',24,48,'power1.inOut');safeTo(tl,'.plank',{y:-12,duration:6,stagger:4,yoyo:true,repeat:1},24)}
    else if(m==='hubConnect'){pathMove(tl,'.hub-token.ht1','#h0',22,24,'power1.inOut');pathMove(tl,'.hub-token.ht2','#h4',52,24,'power1.inOut');safeTo(tl,'.hub-node',{scale:1.05,duration:5,stagger:6,yoyo:true,repeat:1},26)}
    else if(m==='eraMorph'||m==='courseCompare'){safeTo(tl,'.era.old',{x:-25,opacity:.72,duration:20},28);safeTo(tl,'.era.new',{x:-20,scale:1.035,duration:20},50);safeTo(tl,'.era-divider i',{scaleY:1.15,duration:8,yoyo:true,repeat:1},44)}
    else if(m==='codeExecute'){safeTo(tl,'.editor code',{opacity:1,duration:18},20);safeTo(tl,'.compile-arrow',{x:15,duration:5,yoyo:true,repeat:3},40);safeTo(tl,'.rt-node',{scale:1.06,duration:5,stagger:5,yoyo:true,repeat:1},52)}
    else if(m==='graphRoute'){pathMove(tl,'.dag-token','#g1',16,18,'none');safeTo(tl,'.dag-token',{opacity:0,duration:1},36);safeTo(tl,'.dag-node',{scale:1.05,duration:4,stagger:7,yoyo:true,repeat:1},20)}
    else if(m==='layerStack'||m==='stackDepth'){safeTo(tl,'.layer-card,.eco-layer',{y:-18,rotationX:3,duration:16,stagger:5},24);safeTo(tl,'.layer-card,.eco-layer',{y:0,rotationX:0,duration:14,stagger:3},62)}
    else if(m==='traceStream'||m==='traceScrub'){safeTo(tl,'.trace-row>i:after',{scaleX:1,duration:16,stagger:4,transformOrigin:'left'},28);safeTo(tl,'.trace-focus',{scale:1.03,duration:9,yoyo:true,repeat:1},60)}
    else if(m==='filterPass'){safeTo(tl,'.filter-source span',{y:22,opacity:.45,duration:12,stagger:1.5},26);safeTo(tl,'.filter-result span',{y:-8,scale:1.04,duration:8,stagger:2,yoyo:true,repeat:1},50)}
    else if(m==='mapReveal'){safeTo(tl,'.mr.r1',{scale:.96,duration:15,yoyo:true,repeat:1},22);safeTo(tl,'.mr.r2',{scale:1.05,duration:15,yoyo:true,repeat:1},35);safeTo(tl,'.map-question',{y:-8,duration:7,stagger:8,yoyo:true,repeat:1},30)}
    else if(m==='roadmapTravel'){pathMove(tl,'.road-token','#roadPath',18,68,'none');safeTo(tl,'.road-stop',{scale:1.05,duration:5,stagger:12,yoyo:true,repeat:1},22)}
    else if(m==='chapterLaunch'||m==='chapterShift'){safeTo(tl,'.chapter-number',{scale:1.08,opacity:.16,duration:18},18);safeTo(tl,'.chapter-word',{x:22,duration:18},28);safeTo(tl,'.chapter-modules>div',{y:-9,duration:6,stagger:5,yoyo:true,repeat:1},44)}
    else if(m==='toolCall'){pathMove(tl,'.tool-token','#toolPath',18,66,'none');safeTo(tl,'.tool-step',{scale:1.05,duration:5,stagger:9,yoyo:true,repeat:1},20);safeTo(tl,'.tool-schema',{scale:1.04,duration:8,yoyo:true,repeat:1},72)}
    else if(m==='contextLayers'){safeTo(tl,'.context-source',{x:30,duration:11,stagger:4},26);safeTo(tl,'.context-gate',{scale:1.08,duration:8,yoyo:true,repeat:1},48);safeTo(tl,'.context-meter em',{width:'82%',duration:18},58)}
    else if(m==='projectComplete'||m==='kbProject'){pathMove(tl,'.project-token','#projectPath',18,62,'none');safeTo(tl,'.project-card i em',{scaleX:1,duration:12,stagger:5,transformOrigin:'left'},40);safeTo(tl,'.project-done',{scale:1.04,duration:8,yoyo:true,repeat:1},72)}
    else if(m==='gateSequence'){safeTo(tl,'.gate-token',{opacity:1,x:1500,duration:68,ease:'none'},18);safeTo(tl,'.policy-gate',{scale:1.06,duration:4,stagger:8,yoyo:true,repeat:1},24)}
    else if(m==='plugBus'){safeTo(tl,'.bus-token',{opacity:1,x:1180,duration:60,ease:'none'},24);safeTo(tl,'.bus-port',{x:-8,duration:5,stagger:8,yoyo:true,repeat:1},34)}
    else if(m==='delegateOrbit'){safeTo(tl,'.delegate-token.dt1',{opacity:1,x:420,y:-120,duration:24,ease:'power1.inOut'},30);safeTo(tl,'.delegate-token.dt2',{opacity:1,x:1050,y:160,duration:24,ease:'power1.inOut'},46);safeTo(tl,'.agent-card',{scale:1.05,duration:5,stagger:8,yoyo:true,repeat:1},34)}
    else if(m==='uiStream'){safeTo(tl,'.msg.agent',{width:'80%',duration:18},30);safeTo(tl,'.tool-panel>div',{x:-8,duration:5,stagger:8,yoyo:true,repeat:1},42);safeTo(tl,'.stream-panel',{scale:1.03,duration:8,yoyo:true,repeat:1},62)}
    else if(m==='ragOpen'){safeTo(tl,'.rag-token',{opacity:1,x:290,y:-80,duration:20,ease:'power1.inOut'},28);safeTo(tl,'.retrieve-cloud span',{scale:1.05,duration:4,stagger:5,yoyo:true,repeat:1},40);safeTo(tl,'.rag-answer',{scale:1.04,duration:10,yoyo:true,repeat:1},70)}
    else if(m==='vectorFlow'){pathMove(tl,'.vector-token','#vectorPath',18,66,'none');safeTo(tl,'.vp',{scale:1.8,duration:3,stagger:2,yoyo:true,repeat:1},46)}
    else if(m==='funnelDrop'){safeTo(tl,'.doc-cloud i',{x:220,y:110,duration:18,stagger:1.5,opacity:.35},24);safeTo(tl,'.funnel-layer',{scaleX:.96,duration:6,stagger:7,yoyo:true,repeat:1},34);safeTo(tl,'.funnel-result',{scale:1.06,duration:8,yoyo:true,repeat:1},72)}
    else if(m==='graphOpen'){pathMove(tl,'.lg-open-token','#lgo1',34,42,'none');safeTo(tl,'.gn',{scale:1.05,duration:5,stagger:6,yoyo:true,repeat:1},42)}
    else if(m==='stateRoute'){pathMove(tl,'.state-token','#sm1',18,64,'none');safeTo(tl,'.state-node',{scale:1.05,duration:5,stagger:9,yoyo:true,repeat:1},22)}
    else if(m==='approvalPause'){pathMove(tl,'.approval-token','#approvePath',16,54,'none');safeTo(tl,'.pause-gate',{scale:1.08,duration:10,yoyo:true,repeat:1},43);safeTo(tl,'.approve-step.a4',{scale:1.05,duration:8,yoyo:true,repeat:1},72)}
    else if(m==='finalAssemble'){safeTo(tl,'.final-module',{scale:1.06,duration:5,stagger:6,yoyo:true,repeat:1},24);safeTo(tl,'.final-core',{scale:1.05,duration:12,yoyo:true,repeat:1},52);safeTo(tl,'.final-ready',{scale:1.04,duration:8,yoyo:true,repeat:1},74)}
    else if(m==='mapDecision'){safeTo(tl,'.decision-route',{scale:1.05,duration:5,stagger:8,yoyo:true,repeat:1},24);safeTo(tl,'.decision-core',{rotation:1.5,duration:10,yoyo:true,repeat:1},54)}
    else if(m==='finale'){pathMove(tl,'.finale-token','#finalePath',24,42,'power1.inOut');safeTo(tl,'.finale-old',{opacity:.55,scale:.96,duration:16},32);safeTo(tl,'.finale-new',{scale:1.06,duration:16},52);safeTo(tl,'.finale-cta',{y:-12,scale:1.04,duration:12},70)}
  }
  function buildTimeline(s){if(sceneTl)sceneTl.kill();if(!window.gsap)return null;const tl=baseTimeline();applyMotion(tl,s);tl.eventCallback('onUpdate',()=>{currentProgress=tl.progress();updateCueHighlight(currentProgress)});return tl}
  function cueIndexForProgress(p){return p<.18?0:p<.39?1:p<.61?2:p<.82?3:4}function updateCueHighlight(p){const idx=cueIndexForProgress(p);$$('.cue-marker').forEach((el,i)=>el.classList.toggle('active',i+1===idx));if(idx!==lastCue&&idx>0&&playing&&!QA){playSfx(idx===4?'chime':idx===1?'whoosh':'tick');lastCue=idx}}
  let audioCtx=null;function playSfx(kind='tick'){if(!soundEnabled||QA)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);const f1=kind==='whoosh'?170:kind==='chime'?650:500,f2=kind==='whoosh'?720:kind==='chime'?980:410,d=kind==='whoosh'?.18:kind==='chime'?.22:.06;osc.type=kind==='chime'?'sine':'triangle';osc.frequency.setValueAtTime(f1,now);osc.frequency.exponentialRampToValueAtTime(f2,now+d);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(kind==='chime'?.026:.015,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+d);osc.start(now);osc.stop(now+d+.02)}catch(_){}}
  function sceneDuration(s){return Math.max(7500,Math.min(16000,(s.narration||s.title||'').length*118))}function drive(){if(!playing||paused)return;let p=currentProgress;if(localAudio[scenes[current].id]&&narration.duration&&Number.isFinite(narration.duration))p=Math.min(1,narration.currentTime/narration.duration);else p=Math.min(1,(performance.now()-fallbackStarted+fallbackOffset)/sceneDuration(scenes[current]));sceneTl?.progress(p);currentProgress=p;if(p>=.999){advance();return}raf=requestAnimationFrame(drive)}
  async function playCurrent(){if(playing&&!paused)return;if(paused){resume();return}playing=true;paused=false;lastCue=cueIndexForProgress(currentProgress)-1;playBtn&&(playBtn.textContent='▶ 播放中');pauseBtn&&(pauseBtn.textContent='⏸ 暂停');const id=scenes[current].id;if(localAudio[id]){narration.src=localAudio[id];narration.currentTime=0;narration.muted=!soundEnabled;narration.onended=advance;try{await narration.play();status&&(status.textContent=`${id} · LOCAL AUDIO · SEMANTIC CUE SYNC`)}catch{fallbackStarted=performance.now();fallbackOffset=currentProgress*sceneDuration(scenes[current]);drive();return}drive()}else{fallbackStarted=performance.now();fallbackOffset=currentProgress*sceneDuration(scenes[current]);status&&(status.textContent=`${id} · VISUAL CUE SYNC · ${PLANS[id]?.visual||''}`);drive()}}
  function pause(){if(!playing)return;if(!paused){paused=true;cancelAnimationFrame(raf);raf=0;narration.pause();pauseBtn&&(pauseBtn.textContent='▶ 继续');status&&(status.textContent='PAUSED · CUE LOCKED')}else resume()}function resume(){if(!playing)return;paused=false;pauseBtn&&(pauseBtn.textContent='⏸ 暂停');if(localAudio[scenes[current].id])narration.play().catch(()=>{});else{fallbackStarted=performance.now();fallbackOffset=currentProgress*sceneDuration(scenes[current])}drive()}function advance(){cancelAnimationFrame(raf);raf=0;narration.pause();if(current<scenes.length-1){current++;render();playCurrent()}else{playing=false;playBtn&&(playBtn.textContent='▶ 播放');status&&(status.textContent='FULL VIDEO COMPLETE · 42/42')}}
  function render(){cancelAnimationFrame(raf);raf=0;narration.pause();playing=false;paused=false;currentProgress=0;lastCue=-1;const s=scenes[current],p=PLANS[s.id]||{};root.innerHTML=R.render(s);chapterLabel&&(chapterLabel.innerHTML=`<i></i>${DATA.project.toUpperCase()}`);countLabel&&(countLabel.textContent=`${String(current+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`);chapterNav&&(chapterNav.textContent=CH[s.chapter]?.title||'');status&&(status.textContent=`${s.id} · ${p.logic||s.title} · READY`);if(scrub){scrub.max=scenes.length-1;scrub.value=current}sceneTl=buildTimeline(s);sceneTl?.progress(QA?1:.035);narration.src=localAudio[s.id]||'';fit()}
  function show(n){current=Math.max(0,Math.min(scenes.length-1,n));render()}function syncSound(){if(narration)narration.muted=!soundEnabled;if(soundBtn){soundBtn.textContent=soundEnabled?'🔊 声音开':'🔇 声音关';soundBtn.classList.toggle('primary',soundEnabled);soundBtn.setAttribute('aria-pressed',soundEnabled?'true':'false')}}
  prevBtn&&(prevBtn.onclick=()=>show(current-1));nextBtn&&(nextBtn.onclick=()=>show(current+1));playBtn&&(playBtn.onclick=playCurrent);pauseBtn&&(pauseBtn.onclick=pause);soundBtn&&(soundBtn.onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem(SOUND_KEY,soundEnabled?'1':'0');syncSound()});fullscreenBtn&&(fullscreenBtn.onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.shell')?.requestFullscreen?.());recordBtn&&(recordBtn.onclick=()=>{const u=new URL('./record.html?v=67-p2-semantic',location.href);const w=window.open(u.href,'project6RecorderControllerP2','popup=yes,width=1500,height=920,resizable=yes');if(!w)alert('浏览器阻止了录制控制台，请允许本站弹出窗口后再点一次。')});scrub&&(scrub.oninput=e=>show(Number(e.target.value)));addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1);if(e.key===' '){e.preventDefault();playing?pause():playCurrent()}});addEventListener('resize',fit);window.addEventListener('message',e=>{if(e.origin!==location.origin)return;const m=e.data||{};if(m.type==='P6_LOCAL_AUDIO'&&m.files){localAudio={...m.files};render()}if(m.type==='P6_CLEAR_AUDIO'){localAudio={};render()}});
  function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function restoreAudio(){try{ownedUrls.forEach(URL.revokeObjectURL);ownedUrls=[];const db=await openDB(),tx=db.transaction(STORE,'readonly'),store=tx.objectStore(STORE),map={};for(let i=1;i<=scenes.length;i++){const id=String(i).padStart(3,'0'),b=await new Promise(r=>{const q=store.get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>r(null)});if(b){const u=URL.createObjectURL(b);ownedUrls.push(u);map[id]=u}}db.close();if(Object.keys(map).length){localAudio=map;render();status&&(status.textContent=`LOCAL AUDIO ${Object.keys(map).length}/${scenes.length} · SEMANTIC CUE SYNC`)}}catch(e){console.warn('P2 audio restore failed',e)}}
  syncSound();fit();render();if(!QA)restoreAudio();if(recordMeta)recordMeta.textContent='P2 · 42 SEMANTIC SCENES · SHOTCRAFT · CUE SYNC';addEventListener('beforeunload',()=>{ownedUrls.forEach(URL.revokeObjectURL);cancelAnimationFrame(raf)});
})();
