(()=>{
  const DATA=window.P6_XIAOHEIYUN_LANGCHAIN,R=window.P6WarmRenderers;if(!DATA||!R)return;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],scenes=DATA.scenes||[];
  const stage=$('#stage'),root=$('#sceneRoot'),chapter=$('#chapterLabel'),count=$('#countLabel'),chapterNav=$('#chapterNav'),status=$('#status'),scrub=$('#scrub'),audio=$('#narration');
  const prev=$('#prevBtn'),next=$('#nextBtn'),play=$('#playBtn'),pause=$('#pauseBtn'),sound=$('#soundBtn'),fullscreen=$('#fullscreenBtn'),record=$('#recordBtn'),meta=$('#recordMeta');
  const chapters=Object.fromEntries((DATA.chapters||[]).map(x=>[x.id,x]));
  let current=Math.max(0,Math.min(scenes.length-1,Number(new URLSearchParams(location.search).get('scene')||1)-1)),tl=null,playing=false,paused=false,raf=0,progress=0,fallbackStart=0,fallbackOffset=0,localAudio={},urls=[],lastCue=-1;
  const QA=new URLSearchParams(location.search).get('qa')==='1',SOUND_KEY='project6.aigc-xiaoheiyun-agent.sound.enabled',DB='project6-aigc-xiaoheiyun-agent-audio',STORE='audio';let soundOn=localStorage.getItem(SOUND_KEY)!=='0';
  if(window.gsap&&window.DrawSVGPlugin)gsap.registerPlugin(DrawSVGPlugin);if(window.gsap&&window.MotionPathPlugin)gsap.registerPlugin(MotionPathPlugin);
  function fit(){const v=$('.viewer'),f=$('.stage-frame');if(!v||!f)return;const r=v.getBoundingClientRect(),s=Math.min(r.width/1920,r.height/1080);f.style.width=1920*s+'px';f.style.height=1080*s+'px';stage.style.transform=`scale(${s})`;stage.style.transformOrigin='0 0'}
  function cueIndex(p){return p<.22?1:p<.48?2:p<.72?3:4}
  let ac=null;function sfx(kind='tick'){if(!soundOn||QA)return;try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();const n=ac.currentTime,o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);const cfg=kind==='whoosh'?[170,620,.16,.012]:kind==='chime'?[600,920,.19,.016]:[480,390,.055,.008];o.type=kind==='chime'?'sine':'triangle';o.frequency.setValueAtTime(cfg[0],n);o.frequency.exponentialRampToValueAtTime(cfg[1],n+cfg[2]);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(cfg[3],n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+cfg[2]);o.start(n);o.stop(n+cfg[2]+.02)}catch(_){}}
  function syncCue(p){const i=cueIndex(p);$$('.cue-marker').forEach((e,n)=>e.classList.toggle('active',n===i-1));if(i!==lastCue&&playing){sfx(i===1?'whoosh':i===4?'chime':'tick');lastCue=i}}
  function addShotcraftMotion(){const path=(sel,token,start,dur)=>{const p=$(sel),t=$(token);if(p&&t&&window.MotionPathPlugin)tl.to(t,{opacity:1,duration:1},start).to(t,{duration:dur,motionPath:{path:p,align:p,alignOrigin:[.5,.5]},ease:'none'},start+1)};if($('.wk-hero')){tl.to('.portal-door>i',{rotationY:-68,duration:12,ease:'power3.inOut'},18);path('#heroP3','.hero-token',30,34)}if($('.wk-limit')){path('#gapPath','.gap-token',24,28);tl.to('.limit-gap',{scale:1.03,duration:5,yoyo:true,repeat:1},48)}if($('.wk-timeline')){path('#timelineMain','.time-token',16,64);tl.to('.cap-band i',{scaleY:1,duration:20,stagger:2,transformOrigin:'bottom'},54)}if($('.wk-enterprise')){path('#entA','.et1',28,26);path('#entD','.et2',46,24)}if($('.wk-compare')){tl.to('.ba-scrub',{left:'76%',duration:7,ease:'power3.out'},18).to('.ba-after',{clipPath:'inset(0 24% 0 0)',duration:7,ease:'power3.out'},18).to('.ba-scrub',{left:'68%',duration:5,ease:'power2.inOut'},25).to('.ba-after',{clipPath:'inset(0 32% 0 0)',duration:5},25).to('.ba-scrub',{left:'42%',duration:17,ease:'power2.inOut'},50).to('.ba-after',{clipPath:'inset(0 58% 0 0)',duration:17,ease:'power2.inOut'},50)}if($('.wk-flow'))path('#flowMain','.flow-token',20,60);if($('.wk-ladder'))tl.to('.ladder-world',{x:-380,y:35,rotationY:4,duration:23,ease:'power2.inOut'},26).to('.ladder-world',{x:-780,y:-20,rotationY:-3,duration:23,ease:'power2.inOut'},54).to('.ladder-world',{x:-470,scale:.82,duration:18,ease:'power2.inOut'},78);if($('.wk-system'))path('#sysLoop','.sys-token',20,68);if($('.wk-bridge'))path('#bridgePath','.bridge-token',22,46);if($('.wk-code')){const pre=$('.terminal pre');if(pre){const full=pre.textContent;pre.textContent='';tl.to({},{duration:1,onUpdate(){pre.textContent=full.slice(0,Math.floor(full.length*this.progress()))}},20)}tl.to('.latency em',{width:'100%',duration:18,stagger:2},56)}if($('.wk-graph'))path('#graphP1','.graph-token',22,16);if($('.wk-stack'))tl.to('.stack-world',{rotationX:3,rotationY:7,y:-24,duration:22,ease:'power2.inOut'},42).to('.stack-world',{rotationX:0,rotationY:0,y:0,duration:16},70);if($('.wk-project'))tl.to('.project-progress i',{width:'100%',duration:42,ease:'none'},38);if($('.wk-roadmap'))path('#roadPath','.road-token',18,65)}
  function buildTimeline(){if(tl)tl.kill();if(!window.gsap)return null;tl=gsap.timeline({paused:true,defaults:{ease:'power3.out'}});gsap.set('.cue',{opacity:0,y:26,filter:'blur(7px)'});gsap.set('.cue-0',{opacity:1,y:0,filter:'blur(0px)'});gsap.set('.wk-path',{drawSVG:'0%'});gsap.set('.wk-token',{opacity:0});gsap.set('.cap-band i',{scaleY:.1,transformOrigin:'bottom'});[1,2,3,4].forEach((n,i)=>tl.to(`.cue-${n}`,{opacity:1,y:0,filter:'blur(0px)',duration:8,stagger:.65},10+i*22));if($$('.wk-path').length)tl.to('.wk-path',{drawSVG:'100%',duration:32,stagger:1.2,ease:'power2.inOut'},14);addShotcraftMotion();tl.eventCallback('onUpdate',()=>{progress=tl.progress();syncCue(progress)});return tl}
  function duration(s){return Math.max(8500,Math.min(15500,String(s.narration||s.title||'').length*118))}
  function drive(){if(!playing||paused)return;let p;if(localAudio[scenes[current].id]&&audio.duration&&Number.isFinite(audio.duration))p=Math.min(1,audio.currentTime/audio.duration);else p=Math.min(1,(performance.now()-fallbackStart+fallbackOffset)/duration(scenes[current]));tl?.progress(p);progress=p;if(p>=.999){advance();return}raf=requestAnimationFrame(drive)}
  async function start(){if(playing&&!paused)return;if(paused){resume();return}playing=true;paused=false;lastCue=-1;play&&(play.textContent='▶ 播放中');const id=scenes[current].id;if(localAudio[id]){audio.src=localAudio[id];audio.currentTime=0;audio.muted=!soundOn;audio.onended=advance;try{await audio.play();status&&(status.textContent=`${id} · LOCAL AUDIO · WORD-LED MOTION`);drive();return}catch(_){}}fallbackStart=performance.now();fallbackOffset=progress*duration(scenes[current]);status&&(status.textContent=`${id} · VISUAL PREVIEW · CUE SYNC`);drive()}
  function pauseToggle(){if(!playing)return;if(!paused){paused=true;cancelAnimationFrame(raf);audio.pause();pause&&(pause.textContent='▶ 继续');status&&(status.textContent='PAUSED · MOTION LOCKED')}else resume()}
  function resume(){paused=false;pause&&(pause.textContent='⏸ 暂停');if(localAudio[scenes[current].id])audio.play().catch(()=>{});else{fallbackStart=performance.now();fallbackOffset=progress*duration(scenes[current])}drive()}
  function advance(){cancelAnimationFrame(raf);audio.pause();if(current<scenes.length-1){current++;render();start()}else{playing=false;play&&(play.textContent='▶ 播放');status&&(status.textContent='FULL VIDEO COMPLETE · 42/42')}}
  function render(){cancelAnimationFrame(raf);audio.pause();playing=false;paused=false;progress=0;lastCue=-1;const s=scenes[current];root.innerHTML=R.render(s);chapter&&(chapter.innerHTML=`<i></i>小黑云 · LANGCHAIN AGENT`);count&&(count.textContent=`${String(current+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`);chapterNav&&(chapterNav.textContent=chapters[s.chapter]?.title||'');status&&(status.textContent=`${s.id} · ${s.title} · WARM KEYNOTE READY`);if(scrub){scrub.max=scenes.length-1;scrub.value=current}buildTimeline();tl?.progress(QA?1:.02);audio.src=localAudio[s.id]||'';fit();if(QA)setTimeout(runQA,120)}
  function show(n){current=Math.max(0,Math.min(scenes.length-1,n));render()}function soundSync(){audio.muted=!soundOn;if(sound){sound.textContent=soundOn?'🔊 声音开':'🔇 声音关';sound.setAttribute('aria-pressed',soundOn?'true':'false')}}
  prev&&(prev.onclick=()=>show(current-1));next&&(next.onclick=()=>show(current+1));play&&(play.onclick=start);pause&&(pause.onclick=pauseToggle);sound&&(sound.onclick=()=>{soundOn=!soundOn;localStorage.setItem(SOUND_KEY,soundOn?'1':'0');soundSync()});fullscreen&&(fullscreen.onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.shell')?.requestFullscreen?.());record&&(record.onclick=()=>window.open('./record.html?v=66-p2-warm','project6RecorderControllerP2','popup=yes,width=1500,height=920,resizable=yes'));scrub&&(scrub.oninput=e=>show(Number(e.target.value)));addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1);if(e.key===' '){e.preventDefault();playing?pauseToggle():start()}});addEventListener('resize',fit);
  function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function restore(){try{urls.forEach(URL.revokeObjectURL);urls=[];const db=await openDB(),tx=db.transaction(STORE,'readonly'),st=tx.objectStore(STORE),m={};for(let i=1;i<=scenes.length;i++){const id=String(i).padStart(3,'0'),blob=await new Promise(r=>{const q=st.get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>r(null)});if(blob){const u=URL.createObjectURL(blob);urls.push(u);m[id]=u}}db.close();if(Object.keys(m).length){localAudio=m;render();status&&(status.textContent=`LOCAL AUDIO ${Object.keys(m).length}/${scenes.length}`)}}catch(e){console.warn(e)}}
  function runQA(){const issues=[],sr=stage.getBoundingClientRect(),scale=sr.width/1920;$$('.wk-card,.wk-head,.wk-take,.wk-cue,.biz-card,.flow-node,.time-node,.graph-node,.system-node,.fault,.ladder-card,.road-card,.project-step').forEach(el=>{const r=el.getBoundingClientRect(),l=(r.left-sr.left)/scale,t=(r.top-sr.top)/scale,rr=(r.right-sr.left)/scale,bb=(r.bottom-sr.top)/scale;if(l<-3||t<-3||rr>1923||bb>1083)issues.push(`OUT:${el.className}`);if(el.scrollWidth>el.clientWidth+4||el.scrollHeight>el.clientHeight+4)issues.push(`CLIP:${el.className}`)});document.documentElement.dataset.qa=JSON.stringify({scene:scenes[current].id,issues})}
  soundSync();fit();render();if(!QA)restore();if(meta)meta.textContent='P2 · 42 SCENES · WARM KEYNOTE · SHOTCRAFT';
})();